version: "3.9"

services:

  db:
    image: postgres:15
    container_name: roster_db
    restart: always
    environment:
      POSTGRES_USER: roster
      POSTGRES_PASSWORD: roster123
      POSTGRES_DB: rosterdb
    ports:
      - "5432:5432"
    volumes:
      - roster_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: roster_api
    depends_on:
      - db
    ports:
      - "80:8000"
    volumes:
      - ./backend:/app

volumes:
  roster_data: